version: "3"
services:
  web:
    build: ./web
    expose:
      - 8001
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    command: gunicorn app.wsgi:application --bind 127.0.0.1:8001
    depends_on:
      - db
    env_file: .env
    environment:
      - DEBUG=FALSE

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume:
