version: "3"
services:
  web:
    build: ./web
    restart: always
    expose:
      - 8000
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file: .env
    environment:
      - DEBUG=FALSE

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    restart: always
    environment:
      VIRTUAL_HOST: mncntrl.ru
    container_name: mncntrl-nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  postgres_data:
  static_volume:
  media_volume:
