version: "3"
services:
  web:
    build: ./web
    restart: always
    expose:
      - 8000
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file: .env
    environment:
      - DEBUG=FALSE

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    restart: always
    container_name: mncntrl-nginx
    volumes:
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
      environment:
        - VIRTUAL_HOST=${DOMAIN}
        - LETSENCRYPT_HOST=${DOMAIN}
        - LETSENCRYPT_EMAIL=${EMAIL_HOST_USER}
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
