# Generated by Django 2.2.10 on 2020-02-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200224_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
