name: Test && Deploy
on:
  push:
    branches: [master]

jobs:
  test-and-deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing...
        run: |
          echo -e "SECRET_KEY=please_change_me\n
          ALLOWED_HOSTS=0.0.0.0,\n
          DOMAIN=example.com,\n
          SQL_ENGINE=django.db.backends.postgresql\n
          SQL_DATABASE=postgres\n
          SQL_USER=postgres\n
          SQL_PASSWORD=password\n
          SQL_HOST=db\n
          SQL_PORT=5432\n
          DATABASE=postgres\n
          EMAIL_HOST_USER=test@example.com\n
          EMAIL_HOST_PASSWORD=please_change_me\n" >> .env
          docker network create proxy-bypass
          make build_prod
          make test_prod

    steps:
      - name: Deploying via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd ./code/moneycontrol-app-api
            git fetch && git pull origin master
            make down_prod
            make up_prod
