name: Test
on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing...
        run: docker network create proxy-bypass
        run: make build_prod
        run: make test_prod
